
ocp:
	cargo run --bin 02ocp
dip:
	cargo run --bin 03dip
crp:
	cargo run --bin 04crp

01simple_factory:
	cargo run --bin 01simple_factory
02factory_method:
	cargo run --bin 02factory_method
03abstract_factory_method:
	cargo run --bin 03abstract_factory_method